// ============================================
// SHARED TENDER STORAGE & UTILITIES
// ============================================

const STORAGE_KEY = 'tenderPortalData';

// Default sample tenders (used if localStorage is empty)
const DEFAULT_TENDERS = [
  {
    id: 't1',
    tenderNo: '01/2026',
    workName: 'Bridge approach road',
    department: 'PWD',
    cost: 4500000,
    date: '2026-02-10',
    status: 'Selected',
    bidder: 'Highway Infra',
    amount: 4470000
  },
  {
    id: 't2',
    tenderNo: '12/2026',
    workName: 'Water supply pipeline',
    department: 'Jal Nigam',
    cost: 2800000,
    date: '2026-03-01',
    status: 'Under Evaluation',
    bidder: '',
    amount: 0
  },
  {
    id: 't3',
    tenderNo: '08/2026',
    workName: 'School roof repair',
    department: 'Education',
    cost: 1200000,
    date: '2026-01-18',
    status: 'Cancelled',
    bidder: 'N/A',
    amount: 0
  }
];

// Load tenders from localStorage, or initialize with defaults
export function loadTenders() {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored) {
    try {
      return JSON.parse(stored);
    } catch (e) {
      return [...DEFAULT_TENDERS];
    }
  } else {
    // First visit: store defaults and return them
    localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_TENDERS));
    return [...DEFAULT_TENDERS];
  }
}

// Save tenders array to localStorage
export function saveTenders(tenders) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(tenders));
  // Dispatch a storage event so other tabs can update (optional)
  window.dispatchEvent(new Event('tendersUpdated'));
}

// Helper: get CSS class for status badge
export function getStatusClass(status) {
  switch (status) {
    case 'Selected': return 'status-selected';
    case 'Cancelled': return 'status-cancelled';
    case 'Under Evaluation': return 'status-evaluation';
    default: return '';
  }
}

// Generate printable PDF layout for a tender
export function generateTenderPDF(tender, autoPrint = false) {
  if (!tender) return;
  const win = window.open('', '_blank');
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Tender ${tender.tenderNo}</title>
      <style>
        body { font-family: 'Inter', Arial; padding: 2rem; color: #1e2f4a; }
        .header { border-bottom: 3px solid #002868; padding-bottom: 0.5rem; margin-bottom: 2rem; }
        h2 { color: #002868; }
        .details { background: #f4faff; padding: 2rem; border-radius: 24px; display: grid; gap: 1.5rem; }
        .row { display: flex; border-bottom: 1px solid #d4e2f0; padding: 0.8rem 0; }
        .label { font-weight: 600; width: 200px; color: #002868; }
        .value { flex: 1; }
        .badge { display: inline-block; padding: 0.3rem 1.2rem; border-radius: 30px; font-weight: 700; }
        .footer { margin-top: 3rem; text-align: center; color: #5f7d9c; font-size: 0.9rem; }
      </style>
    </head>
    <body>
      <div class="header"><h1>TENDER RESULT OFFICIAL</h1></div>
      <h2>${tender.workName} (${tender.tenderNo})</h2>
      <div class="details">
        <div class="row"><span class="label">Department</span><span class="value">${tender.department}</span></div>
        <div class="row"><span class="label">Estimated Cost</span><span class="value">₹ ${Number(tender.cost).toLocaleString()}</span></div>
        <div class="row"><span class="label">Bid Opening Date</span><span class="value">${tender.date}</span></div>
        <div class="row"><span class="label">Status</span><span class="value"><span class="badge" style="background:${tender.status==='Selected'?'#dcfce7':tender.status==='Cancelled'?'#fee2e2':'#fff3cd'};">${tender.status}</span></span></div>
        <div class="row"><span class="label">Selected Bidder</span><span class="value">${tender.bidder || '—'}</span></div>
        <div class="row"><span class="label">Quoted Amount</span><span class="value">₹ ${Number(tender.amount).toLocaleString()}</span></div>
      </div>
      <div class="footer">Generated by Tender Result Portal · ${new Date().toLocaleDateString()}</div>
      ${autoPrint ? '<script>window.onload = () => { window.print(); }</script>' : ''}
    </body>
    </html>
  `);
  win.document.close();
}
